[package]
name = "zerotorrent"
authors = ["Viktor Popp <viktorpopp.dev@gmail.com>"]
description = "Open-Source BitTorrent Client"
version = "0.0.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.51", features = ["derive"] }
serde_json = "1.0.145"
